# https://taskfile.dev

version: '3'

vars:
  USER_NAME: devlights
  APP_NAME: gcw

tasks:
  default:
    cmds:
      - task: run
  build:
    dir: cmd/gcw
    cmds:
      - go build -o {{.APP_NAME}}{{exeExt}} .
    sources:
      - ./*.go
    generates:
      - ./{{.APP_NAME}}{{exeExt}}
  run:
    deps: [ build ]
    dir: cmd/gcw
    cmds:
      - ./{{.APP_NAME}}{{exeExt}} -user {{.USER_NAME}}